server {
    server_name blackmossandherbs.com www.blackmossandherbs.com;

    location / {
        proxy_pass http://127.0.0.1:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Listen on 80 for Certbot/Initial Setup (Will be updated by Certbot)
    listen 80;
}

# Redirects for .co.uk
server {
    server_name blackmossandherbs.co.uk www.blackmossandherbs.co.uk;
    return 301 https://blackmossandherbs.com$request_uri;
    listen 80;
}

# Redirects for .info
server {
    server_name blackmossandherbs.info www.blackmossandherbs.info;
    return 301 https://blackmossandherbs.com$request_uri;
    listen 80;
}
