/**
 * HECTIC Intellectual Property - Copyright 2024
 * Black Moss & Herbs Platform - Content Hub Dashboard
 */

"use client";

import { useState } from 'react';
import { PenTool, Send, Globe, MessageSquare, CheckCircle, RefreshCw, Layers } from 'lucide-react';
import Button from '@/components/Button';

export default function ContentHubPage() {
    const [topic, setTopic] = useState('');
    const [persona, setPersona] = useState('ALCHEMIST');
    const [generating, setGenerating] = useState(false);
    const [draft, setDraft] = useState<any>(null);
    const [deployed, setDeployed] = useState(false);

    const handleGenerate = async () => {
        setGenerating(true);
        setDeployed(false);
        // Simulate API call to AIContentService
        setTimeout(() => {
            setDraft({
                title: topic === 'Sea Moss' ? 'The Alchemical Bio-Chemistry of Sea Moss' : `Autonomous Insights: ${topic}`,
                excerpt: 'A comprehensive analysis generated by The Council.',
                content: 'Full AI content would appear here...',
                socials: {
                    instagram: 'Instagram caption ready...',
                    twitter: 'X/Twitter post ready...',
                }
            });
            setGenerating(false);
        }, 1500);
    };

    const handleDeploy = () => {
        setGenerating(true);
        setTimeout(() => {
            setGenerating(false);
            setDeployed(true);
        }, 1000);
    };

    return (
        <div className="py-12 bg-earth-950 min-h-screen relative overflow-hidden">
            {/* Background Pattern */}
            <div className="absolute inset-0 bg-[url('/patterns/sea-moss-pattern.svg')] bg-repeat opacity-5 pointer-events-none" />

            <div className="container relative z-10">
                <div className="mb-12 flex justify-between items-end">
                    <div>
                        <h1 className="font-serif text-5xl font-bold bg-gradient-to-r from-secondary-400 to-primary-400 bg-clip-text text-transparent mb-2">
                            Content Intelligence
                        </h1>
                        <p className="text-earth-400 text-lg">Autonomous Omnichannel Distribution Hub</p>
                    </div>
                    <div className="bg-earth-900/50 p-1.5 rounded-2xl border border-earth-800 backdrop-blur-md">
                        <button
                            onClick={() => setPersona('ALCHEMIST')}
                            className={`px-6 py-2.5 rounded-xl font-bold text-xs uppercase tracking-widest transition-all ${persona === 'ALCHEMIST' ? 'bg-primary-600 text-white shadow-lg shadow-primary-900/20' : 'text-earth-500 hover:text-earth-300'}`}>
                            Alchemist
                        </button>
                        <button
                            onClick={() => setPersona('CLINICAL')}
                            className={`px-6 py-2.5 rounded-xl font-bold text-xs uppercase tracking-widest transition-all ${persona === 'CLINICAL' ? 'bg-primary-600 text-white shadow-lg shadow-primary-900/20' : 'text-earth-500 hover:text-earth-300'}`}>
                            Clinical
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* controls */}
                    <div className="lg:col-span-1 space-y-6">
                        <div className="card p-8 border border-earth-800 bg-earth-900/40 backdrop-blur-xl">
                            <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-3">
                                <div className="w-10 h-10 bg-primary-900/20 rounded-xl flex items-center justify-center border border-primary-700/30">
                                    <PenTool className="w-5 h-5 text-primary-400" />
                                </div>
                                Authority Draft
                            </h2>
                            <div className="space-y-6">
                                <div>
                                    <label className="block text-xs font-bold text-earth-500 uppercase tracking-widest mb-3">Target Topic</label>
                                    <input
                                        type="text"
                                        className="w-full bg-earth-950/50 border border-earth-800 rounded-2xl py-4 px-6 text-white focus:outline-none focus:border-secondary-500 transition-colors"
                                        placeholder="e.g. Sea Moss Bio-Chemistry"
                                        value={topic}
                                        onChange={(e) => setTopic(e.target.value)}
                                    />
                                </div>
                                <Button
                                    className="w-full py-5 rounded-2xl text-lg font-bold shadow-xl overflow-hidden group relative"
                                    onClick={handleGenerate}
                                    disabled={generating || !topic}>
                                    <div className="absolute inset-0 bg-gradient-to-r from-primary-600 to-secondary-600 opacity-100 group-hover:opacity-90 transition-opacity" />
                                    <span className="relative flex items-center justify-center gap-2">
                                        {generating ? <RefreshCw className="animate-spin" /> : <Layers className="w-5 h-5" />}
                                        Consult The Council
                                    </span>
                                </Button>
                            </div>
                        </div>

                        <div className="card p-8 border border-earth-800 bg-secondary-900/5 backdrop-blur-xl relative overflow-hidden">
                            <div className="absolute -right-8 -top-8 w-32 h-32 bg-secondary-500/5 blur-3xl rounded-full" />

                            <h2 className="text-xl font-bold text-white mb-3">Global Dispersion</h2>
                            <p className="text-sm text-earth-400 mb-6 font-medium">Auto-dispatch current draft to the HECTIC ecosystem:</p>
                            <div className="space-y-4">
                                <div className="flex items-center gap-3 text-sm text-earth-300 font-medium">
                                    <Globe className="w-5 h-5 text-secondary-400" /> Website Wisdom Hub
                                </div>
                                <div className="flex items-center gap-3 text-sm text-earth-300 font-medium">
                                    <MessageSquare className="w-5 h-5 text-secondary-400" /> Instagram & X (Twitter)
                                </div>
                                <div className="flex items-center gap-3 text-sm text-earth-300 font-medium">
                                    <Send className="w-5 h-5 text-secondary-400" /> Member Network (Email)
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Preview Area */}
                    <div className="lg:col-span-2">
                        {draft ? (
                            <div className="space-y-6 animate-fade-in">
                                <div className="card border border-earth-800 bg-earth-900/60 backdrop-blur-xl p-10">
                                    <div className="flex justify-between items-start mb-10">
                                        <div className="flex items-center gap-3">
                                            <span className="px-4 py-1.5 bg-secondary-900/30 text-secondary-400 border border-secondary-800/50 rounded-full text-[10px] font-black uppercase tracking-widest">
                                                {persona} VERIFIED
                                            </span>
                                            <span className="px-4 py-1.5 bg-primary-900/30 text-primary-400 border border-primary-800/50 rounded-full text-[10px] font-black uppercase tracking-widest">
                                                AI-GENERATED
                                            </span>
                                        </div>
                                        <Button
                                            variant="secondary"
                                            onClick={handleDeploy}
                                            disabled={deployed || generating}
                                            className="px-8 py-3 rounded-xl font-bold">
                                            {deployed ? <CheckCircle className="mr-2" /> : <Send className="mr-2" />}
                                            {deployed ? 'Dispersion Complete' : 'Execute Global Publishing'}
                                        </Button>
                                    </div>
                                    <h1 className="text-4xl font-serif font-bold text-white mb-6 leading-tight">{draft.title}</h1>
                                    <div className="space-y-6 text-earth-300">
                                        <p className="font-medium text-xl text-secondary-400 italic bg-secondary-950/20 p-6 rounded-2xl border-l-4 border-secondary-500">
                                            "{draft.excerpt}"
                                        </p>
                                        <div className="p-8 bg-earth-950/50 rounded-3xl border border-earth-800 leading-relaxed text-lg">
                                            {draft.content}
                                        </div>
                                    </div>

                                    <div className="mt-12 grid grid-cols-2 gap-6">
                                        <div className="p-6 bg-earth-900/50 border border-earth-800 rounded-2xl">
                                            <h4 className="font-black text-[10px] mb-4 uppercase text-earth-500 tracking-[0.2em]">Instagram Dispersion</h4>
                                            <p className="text-sm italic text-earth-300 font-medium leading-relaxed">"{draft.socials.instagram}"</p>
                                        </div>
                                        <div className="p-6 bg-earth-900/50 border border-earth-800 rounded-2xl">
                                            <h4 className="font-black text-[10px] mb-4 uppercase text-earth-500 tracking-[0.2em]">X (Twitter) Dispersion</h4>
                                            <p className="text-sm italic text-earth-300 font-medium leading-relaxed">"{draft.socials.twitter}"</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="card h-full flex flex-col items-center justify-center p-20 text-center border-dashed border-2 border-earth-800/50 bg-earth-900/20 rounded-[3rem]">
                                <div className="w-24 h-24 bg-earth-900 border border-earth-800 rounded-3xl flex items-center justify-center mb-8 shadow-2xl">
                                    <PenTool className="w-10 h-10 text-earth-700" />
                                </div>
                                <h3 className="text-3xl font-serif font-bold text-earth-300 mb-4">Command Post Dormant</h3>
                                <p className="text-earth-500 text-lg max-w-sm mx-auto font-medium">Provide a topic core to initiate the autonomous HECTIC content production cycle.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
